# ~/.config/starship.toml

[python]
disabled = true

[custom.git_worktree]
command = 'echo "ðŸŒ²"'
when = ''' test "$(git rev-parse --git-common-dir 2>/dev/null)" != "$(git rev-parse --git-dir 2>/dev/null)" '''
format = '[$output]($style) '
style = 'bold cyan'